
module.exports = [
    {
      name: "Deluxe Suite",
      type: "suite",
      price: 8500,
      status: "empty",
      totalGuests: 4,
    },
    {
      name: "Single Room A",
      type: "single",
      price: 1000,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Double Room B",
      type: "double",
      price: 2200,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Family Suite",
      type: "suite",
      price: 9000,
      status: "empty",
      totalGuests: 5,
    },
    {
      name: "Budget Double Room",
      type: "double",
      price: 1200,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Luxury Suite",
      type: "suite",
      price: 10000,
      status: "empty",
      totalGuests: 4,
    },
    {
      name: "Economy Single Room",
      type: "single",
      price: 800,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Double Room C",
      type: "double",
      price: 1800,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Presidential Suite",
      type: "suite",
      price: 9800,
      status: "empty",
      totalGuests: 5,
    },
    {
      name: "Single Room D",
      type: "single",
      price: 950,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Royal Suite",
      type: "suite",
      price: 9500,
      status: "empty",
      totalGuests: 5,
    },
    {
      name: "Double Room E",
      type: "double",
      price: 1700,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Single Room F",
      type: "single",
      price: 1100,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Business Suite",
      type: "suite",
      price: 8700,
      status: "empty",
      totalGuests: 3,
    },
    {
      name: "Economy Double Room",
      type: "double",
      price: 1300,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Executive Suite",
      type: "suite",
      price: 9400,
      status: "empty",
      totalGuests: 4,
    },
    {
      name: "Single Room G",
      type: "single",
      price: 1050,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Junior Suite",
      type: "suite",
      price: 8900,
      status: "empty",
      totalGuests: 3,
    },
    {
      name: "Penthouse Suite",
      type: "suite",
      price: 10000,
      status: "empty",
      totalGuests: 4,
    },
    {
      name: "Double Room H",
      type: "double",
      price: 1900,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Economy Single Room I",
      type: "single",
      price: 900,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Double Room J",
      type: "double",
      price: 1800,
      status: "empty",
      totalGuests: 2,
    },
    {
      name: "Single Room K",
      type: "single",
      price: 850,
      status: "empty",
      totalGuests: 1,
    },
    {
      name: "Grand Suite",
      type: "suite",
      price: 9200,
      status: "empty",
      totalGuests: 4,
    },
    {
      name: "Family Room L",
      type: "suite",
      price: 8700,
      status: "empty",
      totalGuests: 5,
    },
  ];
  